// Misfits — Ticket Audit Log Window
// Displays all persisted help-ticket lifecycle events from the database so admins can
// review staff conduct and ticket handling across all past rounds.
// #Misfits Change - expanded filters: player name, admin name, date range, month quick-selectors, admin statistics tab
using Content.Client.Administration.Systems;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketAuditLogWindow : DefaultWindow
{
    private readonly BwoinkSystem _bwoinkSys;

    private const int PageSize = 100;
    private int _currentOffset = 0;
    private int _totalCount = 0;
    
    // #Misfits Add - expanded filter fields
    private Guid? _filterPlayerId = null;
    private string? _filterPlayerName = null;
    private string? _filterAdminName = null;
    private Guid? _filterAdminId = null;
    private DateTime? _filterStartDate = null;
    private DateTime? _filterEndDate = null;

    public TicketAuditLogWindow()
    {
        RobustXamlLoader.Load(this);

        var entMan = IoCManager.Resolve<IEntityManager>();
        _bwoinkSys = entMan.System<BwoinkSystem>();
        _bwoinkSys.OnAuditLogReceived += OnAuditLogReceived;

        // #Misfits Change - find and wire up filter controls
        var filterButton = this.FindControl<Button>("FilterButton");
        var clearFilterButton = this.FindControl<Button>("ClearFilterButton");
        var thisMonthButton = this.FindControl<Button>("ThisMonthButton");
        var lastMonthButton = this.FindControl<Button>("LastMonthButton");
        var prevPageButton = this.FindControl<Button>("PrevPageButton");
        var nextPageButton = this.FindControl<Button>("NextPageButton");

        filterButton!.OnPressed += _ => ApplyFilters();
        clearFilterButton!.OnPressed += _ =>
        {
            var playerEdit = this.FindControl<LineEdit>("PlayerFilterEdit")!;
            var adminEdit = this.FindControl<LineEdit>("AdminFilterEdit")!;
            var startEdit = this.FindControl<LineEdit>("StartDateEdit")!;
            var endEdit = this.FindControl<LineEdit>("EndDateEdit")!;
            
            playerEdit.Text = string.Empty;
            adminEdit.Text = string.Empty;
            startEdit.Text = string.Empty;
            endEdit.Text = string.Empty;
            _filterPlayerId = null;
            _filterPlayerName = null;
            _filterAdminName = null;
            _filterAdminId = null;
            _filterStartDate = null;
            _filterEndDate = null;
            _currentOffset = 0;
            Refresh();
        };

        // #Misfits Add - month quick-selector buttons
        thisMonthButton!.OnPressed += _ => SetThisMonth();
        lastMonthButton!.OnPressed += _ => SetLastMonth();

        // Pagination
        prevPageButton!.OnPressed += _ =>
        {
            _currentOffset = Math.Max(0, _currentOffset - PageSize);
            RefreshEvents();
        };

        nextPageButton!.OnPressed += _ =>
        {
            _currentOffset += PageSize;
            RefreshEvents();
        };

        // Load first page immediately
        Refresh();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _bwoinkSys.OnAuditLogReceived -= OnAuditLogReceived;
    }

    // #Misfits Change - parse and validate all filter inputs
    private void ApplyFilters()
    {
        var playerEdit = this.FindControl<LineEdit>("PlayerFilterEdit")!;
        var adminEdit = this.FindControl<LineEdit>("AdminFilterEdit")!;
        var startEdit = this.FindControl<LineEdit>("StartDateEdit")!;
        var endEdit = this.FindControl<LineEdit>("EndDateEdit")!;

        // Parse player filter (can be name or GUID)
        _filterPlayerId = null;
        _filterPlayerName = null;
        var playerText = playerEdit.Text.Trim();
        if (!string.IsNullOrEmpty(playerText))
        {
            if (Guid.TryParse(playerText, out var parsed))
            {
                _filterPlayerId = parsed;
            }
            else
            {
                _filterPlayerName = playerText;
            }
        }

        // Admin name filter
        _filterAdminName = adminEdit.Text.Trim();
        if (string.IsNullOrEmpty(_filterAdminName))
            _filterAdminName = null;

        // Parse date filters
        _filterStartDate = TryParseDate(startEdit.Text.Trim());
        _filterEndDate = TryParseDate(endEdit.Text.Trim());

        _currentOffset = 0;
        Refresh();
    }

    // #Misfits Add - month quick-selector: set dates to current month (starts today, goes to end of month)
    private void SetThisMonth()
    {
        var startEdit = this.FindControl<LineEdit>("StartDateEdit")!;
        var endEdit = this.FindControl<LineEdit>("EndDateEdit")!;
        
        var now = DateTime.Now;
        _filterStartDate = new DateTime(now.Year, now.Month, 1, 0, 0, 0, DateTimeKind.Local);
        _filterEndDate = new DateTime(now.Year, now.Month, DateTime.DaysInMonth(now.Year, now.Month), 23, 59, 59, DateTimeKind.Local);
        
        startEdit.Text = _filterStartDate.Value.ToString("yyyy-MM-dd");
        endEdit.Text = _filterEndDate.Value.ToString("yyyy-MM-dd");
        
        _currentOffset = 0;
        Refresh();
    }

    // #Misfits Add - month quick-selector: set dates to previous month
    private void SetLastMonth()
    {
        var startEdit = this.FindControl<LineEdit>("StartDateEdit")!;
        var endEdit = this.FindControl<LineEdit>("EndDateEdit")!;
        
        var now = DateTime.Now;
        var firstDay = new DateTime(now.Year, now.Month, 1, 0, 0, 0, DateTimeKind.Local);
        var lastMonthEnd = firstDay.AddDays(-1);
        var lastMonthStart = new DateTime(lastMonthEnd.Year, lastMonthEnd.Month, 1, 0, 0, 0, DateTimeKind.Local);
        
        _filterStartDate = lastMonthStart;
        _filterEndDate = new DateTime(lastMonthEnd.Year, lastMonthEnd.Month, DateTime.DaysInMonth(lastMonthEnd.Year, lastMonthEnd.Month), 23, 59, 59, DateTimeKind.Local);
        
        startEdit.Text = _filterStartDate.Value.ToString("yyyy-MM-dd");
        endEdit.Text = _filterEndDate.Value.ToString("yyyy-MM-dd");
        
        _currentOffset = 0;
        Refresh();
    }

    // #Misfits Add - helper to parse date strings (accepts various formats)
    private DateTime? TryParseDate(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return null;

        if (DateTime.TryParse(text, out var parsed))
        {
            // Convert to UTC for consistency with server
            return DateTime.SpecifyKind(parsed, DateTimeKind.Local).ToUniversalTime();
        }

        return null;
    }

    private void Refresh()
    {
        RefreshEvents();
    }

    private void RefreshEvents()
    {
        // #Misfits Change - pass all filters and request stats on first load of visible period
        var requestStats = _currentOffset == 0;
        _bwoinkSys.RequestAuditLog(
            filterPlayerId: _filterPlayerId,
            limit: PageSize,
            offset: _currentOffset,
            filterPlayerName: _filterPlayerName,
            filterAdminName: _filterAdminName,
            filterAdminId: _filterAdminId,
            filterStartDate: _filterStartDate,
            filterEndDate: _filterEndDate,
            includeAdminStats: requestStats);
    }

    private void OnAuditLogReceived(HelpTicketAuditResponseMessage msg)
    {
        // #Misfits Fix — guard against events firing on a disposed window.
        if (Disposed)
            return;

        _totalCount = msg.TotalCount;
        _currentOffset = msg.Offset;

        // Get controls via FindControl pattern
        var eventList = this.FindControl<BoxContainer>("EventList");
        var pageLabel = this.FindControl<Label>("PageLabel");
        var prevPageButton = this.FindControl<Button>("PrevPageButton");
        var nextPageButton = this.FindControl<Button>("NextPageButton");
        var statsList = this.FindControl<BoxContainer>("StatsList");

        if (eventList == null || pageLabel == null || prevPageButton == null || nextPageButton == null)
            return;

        // Rebuild the events list
        eventList.DisposeAllChildren();

        if (msg.Entries.Count == 0)
        {
            eventList.AddChild(new Label
            {
                Text = Loc.GetString("ticket-audit-log-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 16),
            });
        }
        else
        {
            foreach (var entry in msg.Entries)
            {
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };

                var timeStr = entry.OccurredAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
                var eventStr = entry.EventType switch
                {
                    HelpTicketEventType.Created     => Loc.GetString("ticket-audit-event-created"),
                    HelpTicketEventType.Claimed     => Loc.GetString("ticket-audit-event-claimed"),
                    HelpTicketEventType.Unclaimed   => Loc.GetString("ticket-audit-event-unclaimed"),
                    HelpTicketEventType.Resolved    => Loc.GetString("ticket-audit-event-resolved"),
                    HelpTicketEventType.Reopened    => Loc.GetString("ticket-audit-event-reopened"),
                    HelpTicketEventType.AutoResolved => Loc.GetString("ticket-audit-event-auto-resolved"),
                    _ => entry.EventType.ToString(),
                };

                row.AddChild(new Label { Text = timeStr,                          MinWidth = 140, ClipText = true });
                row.AddChild(new Label { Text = $"#{entry.TicketId}",             MinWidth = 50,  ClipText = true });
                row.AddChild(new Label { Text = eventStr,                         MinWidth = 110, ClipText = true });
                row.AddChild(new Label { Text = entry.PlayerName,                 MinWidth = 170, ClipText = true });
                row.AddChild(new Label { Text = entry.AdminName ?? "-",           MinWidth = 150, ClipText = true });

                eventList.AddChild(row);
            }
        }

        // Update pagination
        var page = (_currentOffset / PageSize) + 1;
        var totalPages = Math.Max(1, (int) Math.Ceiling(_totalCount / (double) PageSize));
        pageLabel.Text = Loc.GetString("ticket-audit-pagination-label", ("page", page), ("total", totalPages), ("count", _totalCount));

        prevPageButton.Disabled = _currentOffset <= 0;
        nextPageButton.Disabled = _currentOffset + PageSize >= _totalCount;

        // #Misfits Add - populate statistics tab if stats were included in response
        if (msg.AdminStats != null && statsList != null)
        {
            PopulateStatistics(msg.AdminStats, statsList);
        }
    }

    // #Misfits Add - display admin statistics in the statistics tab
    private void PopulateStatistics(List<AdminStatEntry> stats, BoxContainer? statsList = null)
    {
        if (statsList == null)
            statsList = this.FindControl<BoxContainer>("StatsList");

        if (statsList == null)
            return;

        statsList.DisposeAllChildren();

        if (stats.Count == 0)
        {
            statsList.AddChild(new Label
            {
                Text = Loc.GetString("ticket-audit-stats-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 16),
            });
        }
        else
        {
            foreach (var stat in stats)
            {
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
                row.AddChild(new Label { Text = stat.AdminName,              MinWidth = 200, ClipText = true });
                row.AddChild(new Label { Text = stat.ResolvedCount.ToString(), MinWidth = 120, HorizontalAlignment = HAlignment.Center });
                row.AddChild(new Label { Text = stat.ClaimedCount.ToString(),  HorizontalExpand = true, HorizontalAlignment = HAlignment.Center });
                statsList.AddChild(row);
            }
        }
    }
}

