// #Misfits Change /Add/ - Loremaster admin tab code-behind.
// Exposes faction objective state to admins and allows issuing new objectives to the highest-ranking
// online faction member. Objective display mirrors the style of the C character menu.
using System.Numerics;
using Content.Client._Misfits.Administration;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Localization;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class LoreMasterTab : Control
{
    // ── Faction catalogue ──────────────────────────────────────────────────

    /// <summary>Display name → prototype faction ID mapping shown in the faction dropdown.</summary>
    private static readonly List<(string Display, string Id)> Factions = new()
    {
        ("NCR",                  "NCR"),
        ("Brotherhood of Steel", "BrotherhoodOfSteel"),
        ("Caesar's Legion",      "CaesarLegion"),
    };

    /// <summary>
    /// Per-faction objective choices exposed in the "Issue" selector.
    /// Keyed by faction prototype ID. Each entry is (display label, objective entity prototype ID).
    /// </summary>
    private static readonly Dictionary<string, List<(string Display, string Proto)>> FactionObjectives = new()
    {
        ["NCR"] = new()
        {
            (Loc.GetString("loremaster-obj-ncr-kill"),          "KillNCRHeadObjective"),
            (Loc.GetString("loremaster-obj-ncr-steal-enclave"), "NCRStealObjective"),
            (Loc.GetString("loremaster-obj-ncr-steal-bosw"),    "NCRStealBOSWObjective"),
            (Loc.GetString("loremaster-obj-ncr-steal-legion"),  "NCRStealLegionObjective"),
        },
        ["BrotherhoodOfSteel"] = new()
        {
            (Loc.GetString("loremaster-obj-bosw-kill"),          "KillBOSWHeadObjective"),
            (Loc.GetString("loremaster-obj-bosw-steal-geck"),    "BOSWStealObjective"),
            (Loc.GetString("loremaster-obj-bosw-steal-ncr"),     "BOSWStealNCRObjective"),
            (Loc.GetString("loremaster-obj-bosw-steal-legion"),  "BOSWStealLegionObjective"),
        },
        ["CaesarLegion"] = new()
        {
            (Loc.GetString("loremaster-obj-legion-kill"),           "KillLegionHeadObjective"),
            (Loc.GetString("loremaster-obj-legion-steal-ncr"),      "LegionStealNCRObjective"),
            (Loc.GetString("loremaster-obj-legion-steal-bosw"),     "LegionStealBOSWObjective"),
            (Loc.GetString("loremaster-obj-legion-steal-enclave"),  "LegionStealEnclaveObjective"),
        },
    };

    // ── IoC refs ───────────────────────────────────────────────────────────

    private LoreMasterClientSystem _loreMaster = default!;

    // ── Constructor ────────────────────────────────────────────────────────

    public LoreMasterTab()
    {
        RobustXamlLoader.Load(this);
        _loreMaster = IoCManager.Resolve<IEntityManager>().System<LoreMasterClientSystem>();

        // Populate faction dropdown
        foreach (var (display, _) in Factions)
            FactionSelector.AddItem(display);

        // #Misfits Change /Fix/ - OnItemSelected fires BEFORE SelectedId is updated; call Select() to commit it first.
        FactionSelector.OnItemSelected += args => { FactionSelector.Select(args.Id); OnFactionChanged(); };
        RefreshButton.OnPressed += _ => RequestRefresh();
        IssueButton.OnPressed += _ => OnIssuePressed();
        IssueCustomButton.OnPressed += _ => OnIssueCustomPressed(); // #Misfits Add

        OnFactionChanged();
    }

    // ── Control lifecycle ─────────────────────────────────────────────────

    protected override void EnteredTree()
    {
        base.EnteredTree();
        // #Misfits Change /Fix/ - subscribe to C# events on the client system, NOT the entity bus.
        // The entity event bus is locked after Initialize(); UI controls must never call SubscribeEvent at runtime.
        _loreMaster.OnFactionInfoReceived += OnFactionInfo;
        _loreMaster.OnObjectiveResultReceived += OnObjectiveResult;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _loreMaster.OnFactionInfoReceived -= OnFactionInfo;
        _loreMaster.OnObjectiveResultReceived -= OnObjectiveResult;
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private string CurrentFactionId => Factions[FactionSelector.SelectedId].Id;

    private void OnFactionChanged()
    {
        ObjectiveSelector.Clear();
        if (FactionObjectives.TryGetValue(CurrentFactionId, out var objectives))
        {
            foreach (var (display, _) in objectives)
                ObjectiveSelector.AddItem(display);
        }

        MembersContainer.RemoveAllChildren();
        StatusLabel.Text = string.Empty;
        ResultLabel.Text = string.Empty;
        TargetLabel.Text = Loc.GetString("loremaster-tab-target-none");
    }

    private void RequestRefresh()
    {
        StatusLabel.Text = Loc.GetString("loremaster-tab-refreshing");
        _loreMaster.RequestFactionInfo(CurrentFactionId);
    }

    // ── Network handlers ───────────────────────────────────────────────────

    private void OnFactionInfo(LoreMasterFactionInfoEvent msg)
    {
        if (msg.FactionId != CurrentFactionId)
            return;

        MembersContainer.RemoveAllChildren();
        StatusLabel.Text = Loc.GetString("loremaster-tab-member-count", ("count", msg.Members.Count));

        if (msg.Members.Count == 0)
        {
            MembersContainer.AddChild(new Label
            {
                Text = Loc.GetString("loremaster-tab-no-members"),
                Modulate = Color.Gray,
            });
            TargetLabel.Text = Loc.GetString("loremaster-tab-target-none");
            return;
        }

        var highest = msg.Members[0];
        TargetLabel.Text = Loc.GetString("loremaster-tab-target-label",
            ("name", highest.PlayerName), ("job", highest.JobName));

        foreach (var member in msg.Members)
        {
            var isTop = member == highest;

            // Member header — star-mark the highest-ranking member so the admin knows who will receive orders
            MembersContainer.AddChild(new Label
            {
                Text = $"{(isTop ? "★ " : "  ")}{member.PlayerName}  [{member.JobName}]",
                Modulate = isTop ? Color.LightSkyBlue : Color.LightGray,
            });

            if (member.Objectives.Count == 0)
            {
                MembersContainer.AddChild(new Label
                {
                    Text = Loc.GetString("loremaster-tab-no-objectives"),
                    Modulate = Color.Gray,
                });
            }
            else
            {
                foreach (var obj in member.Objectives)
                {
                    // Progress bar row styled to match ObjectiveConditionsControl colour convention:
                    // green = complete, white = in-progress
                    var pct = (int)(obj.Progress * 100f);
                    MembersContainer.AddChild(new Label
                    {
                        Text = $"   [{pct,3}%]  {obj.Title}",
                        Modulate = obj.Progress >= 1f ? Color.LimeGreen : Color.White,
                    });
                    if (!string.IsNullOrWhiteSpace(obj.Description))
                    {
                        MembersContainer.AddChild(new Label
                        {
                            Text = $"          {obj.Description}",
                            Modulate = new Color(0.55f, 0.55f, 0.55f), // dim grey
                        });
                    }
                }
            }

            // Small spacer between members
            MembersContainer.AddChild(new Control { MinSize = new Vector2(0, 6) });
        }
    }

    private void OnObjectiveResult(LoreMasterObjectiveResultEvent msg)
    {
        ResultLabel.Text = msg.Message;
        ResultLabel.Modulate = msg.Success ? Color.LimeGreen : Color.OrangeRed;

        if (msg.Success)
            RequestRefresh(); // auto-refresh to show the newly issued objective
    }

    private void OnIssuePressed()
    {
        if (!FactionObjectives.TryGetValue(CurrentFactionId, out var objectives))
            return;
        if (ObjectiveSelector.ItemCount == 0)
            return;
        var idx = ObjectiveSelector.SelectedId;
        if (idx < 0 || idx >= objectives.Count)
            return;

        var proto = objectives[idx].Proto;
        ResultLabel.Text = Loc.GetString("loremaster-tab-issuing");
        ResultLabel.Modulate = Color.Yellow;

        _loreMaster.IssueObjective(CurrentFactionId, proto);
    }

    // #Misfits Add - issue a fully admin-typed (freeform) objective to the top-ranked faction member.
    private void OnIssueCustomPressed()
    {
        var title = CustomTitleEdit.Text.Trim();
        if (string.IsNullOrEmpty(title))
        {
            ResultLabel.Text = Loc.GetString("loremaster-tab-custom-error-no-title");
            ResultLabel.Modulate = Color.OrangeRed;
            return;
        }

        ResultLabel.Text = Loc.GetString("loremaster-tab-issuing");
        ResultLabel.Modulate = Color.Yellow;

        _loreMaster.IssueCustomObjective(CurrentFactionId, title, CustomDescEdit.Text.Trim());
    }
}
