// #Misfits Change - Staff Panel tab for admin menu (quick action buttons; stats moved to TicketStatsTab)
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StaffTab : Control
{
    private TicketLogWindow? _ticketLogWindow;

    public StaffTab()
    {
        RobustXamlLoader.Load(this);

        // Ticket log button
        OpenTicketLog.OnPressed += _ =>
        {
            if (_ticketLogWindow is { Disposed: false })
            {
                _ticketLogWindow.MoveToFront();
                return;
            }

            _ticketLogWindow = new TicketLogWindow();
            _ticketLogWindow.OnClose += () => _ticketLogWindow = null; // Clear reference on close
            _ticketLogWindow.OpenCentered();
        };
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _ticketLogWindow?.Close();
    }
}
