// #Misfits Add - Code-behind for the admin Force War GUI panel.
// Allows admins to declare wars between any two factions, bypassing all cooldowns and rank checks.
// Also allows admins to force-ceasefire any active or pending war.

using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

/// <summary>
/// Admin-only Force War window. Selects aggressor + target from all war-capable factions,
/// optional casus belli, and fires the event to the server.
/// Also includes a Force Ceasefire section listing active wars.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ForceWarWindow : FancyWindow
{
    /// <summary>Fired when the admin clicks Force War. Args: (aggressorId, targetId, casusBelli).</summary>
    public event Action<string, string, string>? OnForceWar;

    /// <summary>Fired when the admin clicks Force Ceasefire. Args: (aggressorId, targetId).</summary>
    public event Action<string, string>? OnForceCeasefire;

    // Ordered list of faction IDs matching the OptionButton indices.
    private readonly List<string> _factionIds = new();

    // Tracks active wars for the ceasefire dropdown.
    private readonly List<FactionWarEntry> _activeWarEntries = new();

    public ForceWarWindow()
    {
        RobustXamlLoader.Load(this);

        // Populate both declare-war selectors with all war-capable factions.
        foreach (var factionId in FactionWarConfig.WarCapableFactions)
        {
            _factionIds.Add(factionId);
            var display = FactionWarConfig.FactionDisplayName(factionId);
            AggressorSelector.AddItem(display);
            TargetSelector.AddItem(display);
        }

        // Default target to second item if available to avoid same-faction default.
        if (_factionIds.Count > 1)
            TargetSelector.SelectId(1);

        // Commit dropdown selection when the user picks an item.
        AggressorSelector.OnItemSelected += args => AggressorSelector.SelectId(args.Id);
        TargetSelector.OnItemSelected    += args => TargetSelector.SelectId(args.Id);
        CeasefireWarSelector.OnItemSelected += args => CeasefireWarSelector.SelectId(args.Id);

        ForceWarButton.OnPressed += _ => SubmitForceWar();
        ForceCeasefireButton.OnPressed += _ => SubmitForceCeasefire();
    }

    /// <summary>
    /// Update the ceasefire section with the current list of active wars.
    /// Called by FactionWarClientSystem when war state changes.
    /// </summary>
    public void UpdateActiveWars(IReadOnlyList<FactionWarEntry> activeWars)
    {
        _activeWarEntries.Clear();
        CeasefireWarSelector.Clear();

        foreach (var war in activeWars)
        {
            _activeWarEntries.Add(war);
            var phaseTag = war.Phase == WarPhase.Pending ? "[PENDING] " : "";
            var label = $"{phaseTag}{FactionWarConfig.FactionDisplayName(war.AggressorFaction)}" +
                        $" vs {FactionWarConfig.FactionDisplayName(war.TargetFaction)}";
            CeasefireWarSelector.AddItem(label);
        }

        ForceCeasefireButton.Disabled = activeWars.Count == 0;
    }

    /// <summary>Display a success or error message in the declare-war result label.</summary>
    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    /// <summary>Display a success or error message in the ceasefire result label.</summary>
    public void ShowCeasefireResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        CeasefireResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    private void SubmitForceWar()
    {
        var aggIdx = AggressorSelector.SelectedId;
        var tgtIdx = TargetSelector.SelectedId;

        if (aggIdx < 0 || aggIdx >= _factionIds.Count ||
            tgtIdx < 0 || tgtIdx >= _factionIds.Count)
            return;

        var aggressorId = _factionIds[aggIdx];
        var targetId    = _factionIds[tgtIdx];

        if (aggressorId == targetId)
        {
            ShowResult(false, "Aggressor and target cannot be the same faction.");
            return;
        }

        // Use placeholder if casus belli is empty.
        var casus = CasusBelliEdit.Text.Trim();
        if (string.IsNullOrEmpty(casus))
            casus = "Admin-forced war (testing)";

        OnForceWar?.Invoke(aggressorId, targetId, casus);
    }

    private void SubmitForceCeasefire()
    {
        var idx = CeasefireWarSelector.SelectedId;
        if (idx < 0 || idx >= _activeWarEntries.Count)
            return;

        var war = _activeWarEntries[idx];
        OnForceCeasefire?.Invoke(war.AggressorFaction, war.TargetFaction);
    }
}
