using System;
using System.Collections.Generic;
using Content.Shared._Misfits.Holotape;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

// #Misfits Add - Code-behind for the holotape/terminal viewer window.
// Renders content in green monospace text on a black background.
// #Misfits Add - Tab switching between DATA and NOTES views.

namespace Content.Client._Misfits.Holotape;

/// <summary>
/// Green-on-black terminal-style window for reading holotapes and terminal entries.
/// Supports a NOTES tab for persistent player-written notes on terminals.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HolotapeWindow : DefaultWindow
{
    // Vault-Tec terminal green
    private const string TermGreen = "#33FF33";
    private const string TermDimGreen = "#1a5c1a";

    // Events fired to the BUI for message sending
    /// <summary>Fired when the user clicks Submit Note.</summary>
    public event Action<string, string>? OnSubmitNote;

    /// <summary>Fired when the user clicks delete on a note. Carries the note Guid.</summary>
    public event Action<Guid>? OnDeleteNote;

    /// <summary>Fired when the user switches to the Notes tab (requests fresh data).</summary>
    public event Action? OnRequestNotes;

    /// <summary>Whether we're currently showing the notes tab.</summary>
    private bool _showingNotes;

    /// <summary>The viewer's own user ID, used to show delete buttons on own notes.</summary>
    private NetUserId? _viewerUserId;

    /// <summary>Whether this terminal has notebook capability (controls tab bar visibility).</summary>
    private bool _hasNotebook;

    public HolotapeWindow()
    {
        RobustXamlLoader.Load(this);

        // Apply terminal-style backgrounds programmatically
        BackgroundPanel.PanelOverride = new StyleBoxFlat(Color.FromHex("#0a0a0a"));
        SepTop.PanelOverride = new StyleBoxFlat(Color.FromHex("#1a5c1a"));
        SepMid.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepBot.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepNotes.PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f"));

        // Tab button styling
        DataTabButton.OnPressed += _ => SwitchToDataTab();
        NotesTabButton.OnPressed += _ => SwitchToNotesTab();

        // Submit button
        SubmitNoteButton.OnPressed += _ => HandleSubmit();
    }

    // ── Public API ───────────────────────────────────────────────────────────

    /// <summary>
    /// Switches the window header and title bar between holotape-item mode and terminal mode.
    /// Holotape items display "HOLOTAPE PLAYER"; built-in terminals display "TERMLINK PROTOCOL".
    /// </summary>
    // #Misfits Add - Dynamic header switch: HOLOTAPE item vs built-in TERMINAL
    public void SetHolotapeMode(bool isHolotapeItem)
    {
        if (isHolotapeItem)
        {
            Title = "HOLOTAPE";
            HeaderLabel.Text = "ROBCO INDUSTRIES (TM) HOLOTAPE PLAYER";
        }
        else
        {
            Title = "TERMINAL";
            HeaderLabel.Text = "ROBCO INDUSTRIES (TM) TERMLINK PROTOCOL";
        }
    }

    /// <summary>
    /// Updates both the title and body content labels with green terminal text.
    /// </summary>
    public void UpdateContent(string title, string content)
    {
        // Build title message with green color
        var titleMsg = new FormattedMessage();
        if (!string.IsNullOrEmpty(title))
        {
            titleMsg.PushColor(Color.FromHex(TermGreen));
            titleMsg.AddMarkupPermissive($"[bold]> {title}[/bold]");
            titleMsg.Pop();
        }
        EntryTitleLabel.SetMessage(titleMsg);

        // Build content message with green color
        var contentMsg = new FormattedMessage();
        if (!string.IsNullOrEmpty(content))
        {
            contentMsg.PushColor(Color.FromHex(TermGreen));
            contentMsg.AddMarkupPermissive(content);
            contentMsg.Pop();
        }
        ContentLabel.SetMessage(contentMsg);
    }

    /// <summary>
    /// Updates the notes list display and enables the tab bar.
    /// Called when state includes notes (terminal has TerminalNotebookComponent).
    /// </summary>
    public void UpdateNotes(List<TerminalNoteEntry>? notes, NetUserId? viewerUserId)
    {
        _viewerUserId = viewerUserId;
        _hasNotebook = notes != null;

        // Show/hide tab bar depending on whether this terminal has a notebook
        TabBar.Visible = _hasNotebook;

        if (notes == null)
        {
            // No notebook — make sure we're on the data tab
            SwitchToDataTab();
            return;
        }

        // Rebuild the notes list UI
        RebuildNotesList(notes);
    }

    // ── Tab Switching ────────────────────────────────────────────────────────

    private void SwitchToDataTab()
    {
        _showingNotes = false;
        DataPanel.Visible = true;
        NotesPanel.Visible = false;
    }

    private void SwitchToNotesTab()
    {
        _showingNotes = true;
        DataPanel.Visible = false;
        NotesPanel.Visible = true;

        // Request fresh notes from server
        OnRequestNotes?.Invoke();
    }

    // ── Notes Rendering ──────────────────────────────────────────────────────

    /// <summary>
    /// Rebuilds the notes list container with all note entries.
    /// </summary>
    private void RebuildNotesList(List<TerminalNoteEntry> notes)
    {
        NotesList.RemoveAllChildren();

        if (notes.Count == 0)
        {
            // Empty state message
            var emptyLabel = new RichTextLabel();
            var emptyMsg = new FormattedMessage();
            emptyMsg.PushColor(Color.FromHex(TermDimGreen));
            emptyMsg.AddText("No notes have been written on this terminal.");
            emptyMsg.Pop();
            emptyLabel.SetMessage(emptyMsg);
            NotesList.AddChild(emptyLabel);
            return;
        }

        foreach (var note in notes)
        {
            // Container for each note
            var noteBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 2,
            };

            // Header: author + timestamp
            var headerLabel = new RichTextLabel();
            var headerMsg = new FormattedMessage();
            headerMsg.PushColor(Color.FromHex(TermGreen));
            headerMsg.AddMarkupPermissive($"[bold]{note.AuthorName}[/bold]  —  {note.Timestamp:yyyy-MM-dd HH:mm}");
            headerMsg.Pop();
            headerLabel.SetMessage(headerMsg);
            noteBox.AddChild(headerLabel);

            // Body text
            var bodyLabel = new RichTextLabel();
            var bodyMsg = new FormattedMessage();
            bodyMsg.PushColor(Color.FromHex(TermGreen));
            bodyMsg.AddText(note.Text);
            bodyMsg.Pop();
            bodyLabel.SetMessage(bodyMsg);
            noteBox.AddChild(bodyLabel);

            // Delete button (only for the note's author)
            if (_viewerUserId != null && note.AuthorUserId == _viewerUserId)
            {
                var deleteBtn = new Button
                {
                    Text = "[ DELETE ]",
                    HorizontalAlignment = HAlignment.Left,
                };
                var noteId = note.Id; // capture for closure
                deleteBtn.OnPressed += _ => OnDeleteNote?.Invoke(noteId);
                noteBox.AddChild(deleteBtn);
            }

            // Dim separator between notes
            var sep = new PanelContainer
            {
                MinHeight = 1,
                HorizontalExpand = true,
                PanelOverride = new StyleBoxFlat(Color.FromHex("#0f3d0f")),
            };
            noteBox.AddChild(sep);

            NotesList.AddChild(noteBox);
        }
    }

    // ── Submit Handler ───────────────────────────────────────────────────────

    private void HandleSubmit()
    {
        var text = NoteInput.Text?.Trim() ?? string.Empty;
        if (string.IsNullOrEmpty(text))
            return;

        // #Misfits Tweak - Author name is now provided by the server (character entity name)
        OnSubmitNote?.Invoke(string.Empty, text);

        // Clear the input after submitting
        NoteInput.Text = string.Empty;
    }
}
